### ISSUE TITLE
Cannot find module 'async'

### ISSUE THREAD

**Issue by lzp729** [zone117x/node-stratum-pool#30]
# new bie to nodejs, test run your code, and got this, how can I solve this?

root@test-server:/mnt/stratum-mining/node_modules# node testlitecoinpool.js 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'async'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/mnt/stratum-mining/node_modules/stratum-pool/lib/pool.js:2:13)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
#     at Module.require (module.js:354:17)

seems module async is missing, not sure if this nodejs lib or your lib, tried npm install async , but no luck, any suggestion?

**Comment by mejores** [comment]
i get this problem too，i cant not solve it
