### ISSUE TITLE
Profit switching process died, spawning replacement

### ISSUE THREAD

**Issue by Elmit2015** [zone117x/node-stratum-pool#96]
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at /home/ronald/nomp/libs/profitSwitch.js:452:36
    at Array.forEach (native)
    at /home/ronald/nomp/libs/profitSwitch.js:450:51
    at /home/ronald/nomp/node_modules/async/lib/async.js:610:21
    at /home/ronald/nomp/node_modules/async/lib/async.js:249:17
    at iterate (/home/ronald/nomp/node_modules/async/lib/async.js:149:13)
    at /home/ronald/nomp/node_modules/async/lib/async.js:160:25
    at /home/ronald/nomp/node_modules/async/lib/async.js:251:21
    at /home/ronald/nomp/node_modules/async/lib/async.js:615:34
    at /home/ronald/nomp/libs/profitSwitch.js:407:25
2014-08-15 14:16:28 [Master]    [Profit] Profit switching process died, spawning replacement...

No switching process started anymore!
How to fix that?
##

**Comment by napoleon2121** [comment]
any news for that ?
